# Soru 1
+ Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.

In [3]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5], dtype=int)
boyut = my_array.ndim
eleman_sayisi = my_array.size

In [4]:
print("Dizi Boyutu:", boyut)
print("Eleman Sayısı:", eleman_sayisi)

Dizi Boyutu: 1
Eleman Sayısı: 5


# Soru 2
+ İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

In [5]:
import numpy as np
three_dimensional_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
boyut = three_dimensional_array.ndim  # Dizi boyutu (bu örnekte 3 olacak)
eleman_sayisi = three_dimensional_array.size  # Dizi içindeki toplam eleman sayısı
katman, satir, sutun = three_dimensional_array.shape  # Dizi katman, satır ve sütun sayıları


In [6]:
print("Dizi Boyutu:", boyut)
print("Eleman Sayısı:", eleman_sayisi)
print("Katman Sayısı:", katman)
print("Satır Sayısı:", satir)
print("Sütun Sayısı:", sutun)


Dizi Boyutu: 3
Eleman Sayısı: 12
Katman Sayısı: 3
Satır Sayısı: 2
Sütun Sayısı: 2


In [7]:
ilk_katman = three_dimensional_array[0]  # İlk katmanı al
ikinci_satir = three_dimensional_array[:, 1, :]  # İkinci satırı al

In [8]:
print("İlk Katman:", ilk_katman)
print("İkinci Satır:", ikinci_satir)

İlk Katman: [[1 2]
 [3 4]]
İkinci Satır: [[ 3  4]
 [ 7  8]
 [11 12]]


# Soru 3
+ Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır

In [11]:
import numpy as np

# Bir boyutlu bir dizi oluşturma
bir_boyutlu = np.array([1, 2, 3, 4, 5])

# Dizi indeksleme
ilk_eleman = bir_boyutlu[0]  # İlk elemanı al
ikinci_eleman = bir_boyutlu[1]  # İkinci elemanı al

print("İlk Eleman:", ilk_eleman)
print("İkinci Eleman:", ikinci_eleman)

# Dizi dilimleme (slicing)
alt_dizi = bir_boyutlu[1:4]  # 2. elemandan 4. elemana kadar olan alt diziyi al

print("Alt Dizi:", alt_dizi)

İlk Eleman: 1
İkinci Eleman: 2
Alt Dizi: [2 3 4]


In [12]:
import numpy as np

# İki boyutlu bir dizi oluşturma
iki_boyutlu = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Dizi indeksleme
birinci_satir = iki_boyutlu[0]  # İlk satırı al
ikinci_sutun = iki_boyutlu[:, 1]  # İkinci sütunu al
birinci_satir_ikinci_eleman = iki_boyutlu[0, 1]  # İlk satırın ikinci elemanını al

print("Birinci Satır:", birinci_satir)
print("İkinci Sütun:", ikinci_sutun)
print("Birinci Satırın İkinci Elemanı:", birinci_satir_ikinci_eleman)

# Dizi dilimleme (slicing)
alt_dizi = iki_boyutlu[1:3, 0:2]  # 2. ve 3. satırları, 1. ve 2. sütunları al

print("Alt Dizi:", alt_dizi)

Birinci Satır: [1 2 3]
İkinci Sütun: [2 5 8]
Birinci Satırın İkinci Elemanı: 2
Alt Dizi: [[4 5]
 [7 8]]


In [13]:
import numpy as np

# Üç boyutlu bir dizi oluşturma
uc_boyutlu = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# Dizi indeksleme
birinci_katman = uc_boyutlu[0]  # İlk katmanı al
ikinci_satir = uc_boyutlu[:, 1, :]  # İkinci katmanın tüm satırlarını al
ucuncu_eleman = uc_boyutlu[2, 1, 0]  # Üçüncü katmanın ikinci satırının ilk elemanını al

print("Birinci Katman:", birinci_katman)
print("İkinci Katmanın Tüm Satırları:", ikinci_satir)
print("Üçüncü Katmanın İkinci Satırının İlk Elemanı:", ucuncu_eleman)

# Dizi dilimleme (slicing)
alt_dizi = uc_boyutlu[1:3, :, 0:1]  # 2. ve 3. katmanları al, tüm satırları ve ilk sütunu al

print("Alt Dizi:", alt_dizi)

Birinci Katman: [[1 2]
 [3 4]]
İkinci Katmanın Tüm Satırları: [[ 3  4]
 [ 7  8]
 [11 12]]
Üçüncü Katmanın İkinci Satırının İlk Elemanı: 11
Alt Dizi: [[[ 5]
  [ 7]]

 [[ 9]
  [11]]]


# Soru 4 
+ Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir.

In [14]:
import numpy as np

# Sıfırlardan oluşan birinci dizi oluşturma (2x3)
zeros_array = np.zeros((2, 3))

# Birlerden oluşan ikinci dizi oluşturma (2x3)
ones_array = np.ones((2, 3))

# Dizileri satır bazında birleştirme (yatay birleştirme)
birlestirilmis_dizi = np.concatenate((zeros_array, ones_array), axis=1)

print("Sıfırlardan Oluşan Dizi:")
print(zeros_array)

print("Birlerden Oluşan Dizi:")
print(ones_array)

print("Birleştirilmiş Dizi:")
print(birlestirilmis_dizi)

Sıfırlardan Oluşan Dizi:
[[0. 0. 0.]
 [0. 0. 0.]]
Birlerden Oluşan Dizi:
[[1. 1. 1.]
 [1. 1. 1.]]
Birleştirilmiş Dizi:
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
